#!bin/sh
. "$(dirname"$0")/_/husky.sh"

echo 'styling,testing and building your project before your commiting'

#check prettier
pnpm check-format || 
(
    echo 'prettier check failed. run pnpm run format,add changes and try commit again'
    false
)
#check eslint
pnpm check-lint ||
(
    echo "eslint checking failed . make the required changes listed above, add changes and try to commit again"
    false
)

#check tsconfig
pnpm check-types ||
(
    echo "failed type check.make the changes required above, add changes and try to commit again"
    false
)

pnpm build || 
(
    echo "your build failed,views the errors above"
    false
)

echo "success commite"